### ISSUE TITLE
Dataset access outside China

### ISSUE THREAD

**Issue by colinlaganier** [zhengli97/DM-KD#1]
Great implementation! However, the pre-trained models and datasets uploaded on Baidu cloud require an account that cannot be created without a Chinese phone number. Could you upload them to another platform for easy access ?

**Comment by zhengli97** [comment]
Thanks for your feedback. The maximum storage limit for Google Drive is 15GB. I can't upload the full 20GB dataset to it. I'm trying to use Onedrive to share the datasets. I'll let you know if this approach works.

**Comment by zhengli97** [comment]
Hi, I have updated README.md and added new OneDrive download links there. Try it and see if it works.

**Comment by colinlaganier** [comment]
That works thank you!
